global:
  scrape_interval: 15s

scrape_configs:
   # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Node Exporter (host machine metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
